import{a as v,S as b,i as d}from"./assets/vendor-LK6CqzKq.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();async function f(r,t){const a={key:"51701755-afeeef66c15ff24568cee0a11",q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t};return(await v.create({baseURL:"https://pixabay.com/api/",params:a}).get()).data}const s={formELem:document.querySelector(".form"),imagesList:document.querySelector(".gallery"),loaderElem:document.querySelector(".loader"),loadMoreElem:document.querySelector(".js-load-more-btn")},p=new b(".img-card a");function h({webformatURL:r,largeImageURL:t,tags:a,likes:i,views:e,comments:o,downloads:c}){return`<li class="img-card">
    <a href="${t}">
    <img src="${r}" alt="${a}">
    </a>
    <ul class="card-text">
    <li class="card-content"><p class="card-content-title">Likes</p><p>${i}</p></li>
    <li class="card-content"><p class="card-content-title">Views</p><p>${e}</p></li>
    <li class="card-content"><p class="card-content-title">Comments</p><p>${o}</p></li>
    <li class="card-content"><p class="card-content-title">Downloads</p><p>${c}</p></li>    
    </ul>
    </li>`}function M(r){const t=r.map(h).join("");s.imagesList.innerHTML=t,p.refresh()}function w(r){const t=r.map(h).join("");s.imagesList.insertAdjacentHTML("beforeend",t),p.refresh()}function E(){s.imagesList.innerHTML=""}function g(){s.loaderElem.classList.remove("visually-hidden")}function m(){s.loaderElem.classList.add("visually-hidden")}function S(){s.loadMoreElem.classList.remove("visually-hidden")}function u(){s.loadMoreElem.classList.add("visually-hidden")}s.formELem.addEventListener("submit",$);s.loadMoreElem.addEventListener("click",x);let n,y,l;function L(){n<y?S():(u(),d.info({message:"We are sorry, but you have reached the end of search results."}))}async function $(r){if(r.preventDefault(),E(),g(),u(),n=1,l=r.target.elements.searchText.value.trim(),!l){m(),d.info({message:"Please enter search words",position:"topRight"});return}try{const t=await f(l,n);y=Math.ceil(t.totalHits/15);const a=t.hits;m(),a.length===0?(d.error({title:"Nothing found!",message:`Sorry, there are no images matching your search "${l}". Please try again!`,position:"topRight"}),u()):(M(a),r.target.reset(),L())}catch{d.error({message:"Sorry, we have connection problems. Please try again!",position:"topRight"})}finally{m()}}async function x(){try{u(),g(),n+=1;const t=(await f(l,n)).hits;w(t),L();const a=document.querySelector(".img-card").getBoundingClientRect();window.scrollBy({top:a.height*2,behavior:"smooth"})}catch{n-=1,d.info({message:"Sorry, we have connection problems!"})}finally{m(),s.loadMoreElem.blur()}}
//# sourceMappingURL=index.js.map
