import{a as d,S as m,i as c}from"./assets/vendor-CLNDzgXJ.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&o(n)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();function u(s){const t={key:"51701755-afeeef66c15ff24568cee0a11",q:s,image_type:"photo",orientation:"horizontal",safesearch:!0};return d.create({baseURL:"https://pixabay.com/api/",params:t}).get().then(o=>o.data).catch(o=>console.log(o))}const a={formELem:document.querySelector(".form"),imagesList:document.querySelector(".gallery"),loaderElem:document.querySelector(".loader-container")},f=new m(".img-card a");function p({webformatURL:s,largeImageURL:t,tags:i,likes:o,views:e,comments:r,downloads:n}){return`<li class="img-card">
    <a href="${t}">
    <img src="${s}" alt="${i}">
    </a>
    <ul class="card-text">
    <li class="card-content"><p class="card-content-title">Likes</p><p>${o}</p></li>
    <li class="card-content"><p class="card-content-title">Views</p><p>${e}</p></li>
    <li class="card-content"><p class="card-content-title">Comments</p><p>${r}</p></li>
    <li class="card-content"><p class="card-content-title">Downloads</p><p>${n}</p></li>    
    </ul>
    </li>`}function g(s){const t=s.map(p).join("");a.imagesList.innerHTML=t,f.refresh()}function h(){a.imagesList.innerHTML=""}function y(){a.loaderElem.classList.remove("visually-hidden")}function l(){a.loaderElem.classList.add("visually-hidden")}a.formELem.addEventListener("submit",L);function L(s){s.preventDefault(),h(),y();const t=s.target.elements.searchText.value.trim();if(t===""){c.info({message:"Please enter search words",position:"topRight"}),l();return}u(t).then(i=>{const o=i.hits;l(),o.length===0?c.error({title:"Nothing found!",message:`Sorry, there are no images matching your search "${t}". Please try again!`,position:"topRight"}):(g(o),s.target.reset())}).catch(i=>{console.log(i),l(),c.error({message:"Sorry, we have connection problems. Please try again!",position:"topRight"})})}
//# sourceMappingURL=index.js.map
