import{a as v,S as b,i as n}from"./assets/vendor-LK6CqzKq.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&c(l)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();async function h(r,t){const a={key:"51701755-afeeef66c15ff24568cee0a11",q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t};return(await v.create({baseURL:"https://pixabay.com/api/",params:a}).get()).data}const s={formELem:document.querySelector(".form"),imagesList:document.querySelector(".gallery"),loaderElem:document.querySelector(".loader"),loadMoreElem:document.querySelector(".js-load-more-btn"),imgCard:document.querySelector(".img-card")},g=new b(".img-card a");function y({webformatURL:r,largeImageURL:t,tags:a,likes:c,views:e,comments:o,downloads:l}){return`<li class="img-card">
    <a href="${t}">
    <img src="${r}" alt="${a}">
    </a>
    <ul class="card-text">
    <li class="card-content"><p class="card-content-title">Likes</p><p>${c}</p></li>
    <li class="card-content"><p class="card-content-title">Views</p><p>${e}</p></li>
    <li class="card-content"><p class="card-content-title">Comments</p><p>${o}</p></li>
    <li class="card-content"><p class="card-content-title">Downloads</p><p>${l}</p></li>    
    </ul>
    </li>`}function w(r){const t=r.map(y).join("");s.imagesList.innerHTML=t,g.refresh()}function E(r){const t=r.map(y).join("");s.imagesList.insertAdjacentHTML("beforeend",t),g.refresh()}function M(){s.imagesList.innerHTML=""}function L(){s.loaderElem.classList.remove("visually-hidden")}function m(){s.loaderElem.classList.add("visually-hidden")}function p(){s.loadMoreElem.classList.remove("visually-hidden")}function u(){s.loadMoreElem.classList.add("visually-hidden")}s.formELem.addEventListener("submit",S);let i,f,d;async function S(r){if(r.preventDefault(),M(),L(),u(),i=1,d=r.target.elements.searchText.value.trim(),d===""){n.info({message:"Please enter search words",position:"topRight"}),m();return}const t=await h(d,i);try{f=Math.ceil(t.totalHits/15);const a=t.hits;m(),a.length===0?(n.error({title:"Nothing found!",message:`Sorry, there are no images matching your search "${d}". Please try again!`,position:"topRight"}),u()):(w(a),r.target.reset()),i<f?p():i===f&&(u(),n.info({message:"We are sorry, but you have reached the end of search results."}))}catch{n.error({message:"Sorry, we have connection problems. Please try again!",position:"topRight"})}m()}s.loadMoreElem.addEventListener("click",$);async function $(){try{if(u(),i<f){i+=1,L();const t=(await h(d,i)).hits;E(t),p(),m();const a=document.querySelector(".img-card").getBoundingClientRect();window.scrollBy({top:a.height*2,behavior:"smooth"}),i===f&&(u(),n.info({message:"We are sorry, but you have reached the end of search results."}))}}catch{i-=1,p(),n.info({message:"Sorry, we have connection problems!"})}m(),s.loadMoreElem.blur()}
//# sourceMappingURL=index.js.map
